# Generated by Django 3.2.12 on 2022-08-08 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updateAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=16)),
                ('cmpname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock.stock')),
                ('symbol', models.CharField(max_length=16)),
                ('country', models.CharField(default='US', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('exchange', models.CharField(default='-', max_length=32)),
                ('ipo', models.DateField(default=datetime.date.today)),
                ('marketCapitalization', models.IntegerField(default=0)),
                ('phone', models.CharField(default='-', max_length=32)),
                ('shareOutstanding', models.FloatField(default=0.0)),
                ('cmpname', models.CharField(default='No data', max_length=32)),
                ('weburl', models.URLField(default='-')),
                ('logo', models.CharField(default='', max_length=256)),
                ('industry', models.CharField(default='-', max_length=32)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
