# Generated by Django 3.2.12 on 2022-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('link', models.URLField(max_length=256)),
            ],
        ),
    ]
