# Generated by Django 3.2.12 on 2022-09-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='assunto',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
