# Generated by Django 3.2.12 on 2022-09-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='link',
        ),
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('link', models.URLField(max_length=256)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
            ],
        ),
    ]
