# Generated by Django 3.2.12 on 2022-11-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_auto_20220924_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=128, unique=True)),
                ('data', models.CharField(max_length=256)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
            ],
        ),
    ]
