# Generated by Django 3.2.12 on 2022-11-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
