# Generated by Django 3.2.12 on 2022-11-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_alter_agenda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(),
        ),
    ]
