# Generated by Django 3.2.12 on 2022-11-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_alter_agenda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tarefa',
            field=models.CharField(max_length=128),
        ),
    ]
