# Generated by Django 3.2.12 on 2022-10-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20221025_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
