# Generated by Django 3.2.12 on 2022-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_user',
            field=models.CharField(default='ALUNO', max_length=256),
        ),
    ]
