# Generated by Django 3.2.12 on 2022-11-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
