# Generated by Django 3.2.12 on 2022-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stockValue', models.FloatField()),
            ],
        ),
    ]
